#/Generator/SingleParticle/particle gamma   
#/Generator/SingleParticle/min_energy 511 keV
#/Generator/SingleParticle/max_energy 511 keV
#/Generator/SingleParticle/region INSIDE_CIGAR
#/Generator/SingleParticle/momentum 0 -1 0
#/Generator/SingleParticle/min_costheta -1
#/Generator/SingleParticle/max_costheta 1
#/Generator/SingleParticle/min_phi 0
#/Generator/SingleParticle/max_phi 3.14
#/Generator/SingleParticle/min_phi 3.14
#/Generator/SingleParticle/max_phi 6.27


/Generator/SingleParticle/particle alpha   
/Generator/SingleParticle/min_energy 5.486 MeV
/Generator/SingleParticle/max_energy 5.486 MeV
/Generator/SingleParticle/region INSIDE_CIGAR
/Generator/SingleParticle/min_costheta 1
/Generator/SingleParticle/max_costheta -1

#/Generator/Kr83mGenerator/region INSIDE_CIGAR
#/Generator/Na22Generator/region INSIDE_CIGAR



/Geometry/Cigar/pressure 1.5 bar
/Geometry/Cigar/fiber_diameter 1 mm
/Geometry/Cigar/coating TPB
/Geometry/Cigar/fiber_type Y11
/Geometry/Cigar/gas Xe

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            1
/nexus/persistency/start_id   0
/nexus/persistency/output_file Cigar_Xe_1.5bar_alpha_tracking.next
