### --------------------------------------------------------
### This init macro simulates realistic atmospheric muons in 
### the Cigar geometry with Xenon gas using cos²θ distribution
### --------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac
/tracking/verbose 0
/nexus/RegisterGeometry Cigar
/nexus/RegisterGenerator RealisticMuonGenerator
/nexus/RegisterPersistencyManager PersistencyManager

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
#/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

### ACTIONS
/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterEventAction DefaultEventAction
/nexus/RegisterTrackingAction DefaultTrackingAction
/nexus/RegisterTrackingAction OpticalTrackingAction
/nexus/RegisterSteppingAction AnalysisSteppingAction

/nexus/RegisterMacro macros/Cigar_Xe_test.config.mac
